# Generated by Django 3.2.5 on 2021-11-05 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('managed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_ordered', models.DateTimeField(blank=True, null=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('I', 'Incomplete'), ('IR', 'In Review'), ('PP', 'Purchase Payment Pending'), ('TP', ' To purchase'), ('P', 'Purchased'), ('R', 'Ready to Ship'), ('IT', 'In Transit'), ('LD', 'Landed'), ('SPP', 'Shipping Payment Pending'), ('RD', 'Ready for Delivery'), ('D', 'Delivered')], max_length=3)),
                ('link', models.URLField(max_length=1000)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('amount_in_purchase_currency', models.FloatField(blank=True, null=True)),
                ('exchage_rate', models.FloatField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('estimated_weight', models.FloatField(blank=True, null=True)),
                ('actual_weight', models.FloatField(blank=True, null=True)),
                ('price_per_kg', models.FloatField(blank=True, null=True)),
                ('shippingEstimate', models.IntegerField(blank=True, null=True)),
                ('shipping', models.IntegerField(blank=True, null=True)),
                ('in_shipment', models.BooleanField(default=False)),
                ('feedback_provided', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CR', 'Created'), ('IT', 'In transit'), ('C', 'Complete')], default='CR', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('P', 'Processing'), ('S', 'Successful'), ('F', 'Failed')], max_length=1)),
                ('type', models.CharField(blank=True, choices=[('D', 'Deposit'), ('W', 'Withdraw')], max_length=1)),
                ('reference', models.CharField(blank=True, max_length=300, null=True)),
                ('payment_mode', models.CharField(blank=True, choices=[('M', 'Mpesa'), ('C', 'Card'), ('I', 'Internal')], max_length=1, null=True)),
                ('message', models.CharField(blank=True, max_length=100, null=True)),
                ('identifier', models.CharField(blank=True, max_length=300, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SRC', 'Ship request created'), ('SRP', 'Ship request processed'), ('PPC', 'Purchase payment completed'), ('IP', 'Item purchased'), ('ETW', 'Enroute to warehouse'), ('RAW', 'Received at warehouse'), ('BPFOS', 'Being prepared for overseas shipping'), ('DFW', 'Departed from warehouse'), ('AADSF', 'Arrived at Dubai sort facility'), ('DTDA', 'Dispatched to destination airport'), ('AADA', 'Arrived at destination airport'), ('UIC', 'Undergoing import clearance'), ('SPP', 'Shipping payment pending'), ('SPC', 'Shipping payment complete'), ('PBPFD', 'Package being prepared for delivery'), ('RFD', 'Ready for delivery'), ('OFD', 'Out for delivery'), ('D', 'Delivered')], max_length=6)),
                ('ship_request_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('ship_request_processed', models.DateTimeField(blank=True, null=True)),
                ('purchase_payment_completed', models.DateTimeField(blank=True, null=True)),
                ('item_purchased', models.DateTimeField(blank=True, null=True)),
                ('enroute_to_warehouse', models.DateTimeField(blank=True, null=True)),
                ('received_at_warehouse', models.DateTimeField(blank=True, null=True)),
                ('being_prepared_for_overseas_shipping', models.DateTimeField(blank=True, null=True)),
                ('departed_from_warehouse', models.DateTimeField(blank=True, null=True)),
                ('arrived_at_dubai_sort_facility', models.DateTimeField(blank=True, null=True)),
                ('dispatched_to_destination_airport', models.DateTimeField(blank=True, null=True)),
                ('arrived_at_destination_airport', models.DateTimeField(blank=True, null=True)),
                ('undergoing_import_clearance', models.DateTimeField(blank=True, null=True)),
                ('package_being_prepared_for_delivery', models.DateTimeField(blank=True, null=True)),
                ('shipping_price_reviewed', models.DateTimeField(blank=True, null=True)),
                ('shipping_payment_complete', models.DateTimeField(blank=True, null=True)),
                ('ready_for_delivery', models.DateTimeField(blank=True, null=True)),
                ('out_for_delivery', models.DateTimeField(blank=True, null=True)),
                ('delivered', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=1000)),
                ('description', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('tax', models.IntegerField(blank=True, null=True)),
                ('shipping', models.IntegerField(blank=True, null=True)),
                ('in_shipment', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('I', 'Incomplete'), ('IR', 'In Review'), ('PP', 'Payment Pending'), ('R', 'Ready to Ship'), ('IT', 'In Transit'), ('RD', 'Ready for Delivery'), ('D', 'Delivered')], max_length=2)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.order')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.shipment')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.shipment'),
        ),
        migrations.CreateModel(
            name='MpesaPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('checkout_RequestID', models.CharField(blank=True, max_length=100, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.CharField(blank=True, max_length=100, null=True)),
                ('date_initiated', models.DateTimeField(auto_now_add=True)),
                ('date_completed', models.DateTimeField(null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(blank=True, max_length=500, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.order')),
            ],
        ),
        migrations.CreateModel(
            name='BatchTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CR', 'Created'), ('DTDA', 'Dispatched to destination airport'), ('AADA', 'Arrived at destination airport'), ('UIC', 'Undergoing import clearance'), ('C', 'Complete')], default='CR', max_length=6)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('dispatched_to_destination_airport', models.DateTimeField(blank=True, null=True)),
                ('arrived_at_destination_airport', models.DateTimeField(blank=True, null=True)),
                ('undergoing_import_clearance', models.DateTimeField(blank=True, null=True)),
                ('complete', models.DateTimeField(blank=True, null=True)),
                ('shipment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.shipment')),
            ],
        ),
    ]
