# Generated by Django 3.2.5 on 2021-11-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertimeline',
            name='ship_request_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
