# Generated by Django 3.2.5 on 2021-11-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20211120_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertimeline',
            name='delivery_details_entered',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
