# Generated by Django 3.2.5 on 2021-11-27 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_ordertimeline_delivery_details_entered'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectPaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service.order')),
            ],
        ),
    ]
