# Generated by Django 3.2.5 on 2021-12-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_alter_rejectpaymentrequest_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('I', 'Incomplete'), ('IR', 'In Review'), ('PP', 'Purchase Payment Pending'), ('TP', ' To purchase'), ('P', 'Purchased'), ('R', 'Ready to Ship'), ('IT', 'In Transit'), ('LD', 'Landed. Pending delivery details'), ('DDE', 'Delivery details entered'), ('SPP', 'Shipping Payment Pending'), ('RD', 'Ready for Delivery'), ('D', 'Delivered'), ('RJ', 'Rejected')], max_length=3),
        ),
        migrations.AlterField(
            model_name='ordertimeline',
            name='status',
            field=models.CharField(choices=[('SRC', 'Ship request created'), ('SRP', 'Ship request processed'), ('PPC', 'Purchase payment completed'), ('IP', 'Item purchased'), ('ETW', 'Enroute to warehouse'), ('RAW', 'Received at warehouse'), ('BPFOS', 'Being prepared for overseas shipping'), ('DFW', 'Departed from warehouse'), ('AADSF', 'Arrived at Dubai sort facility'), ('DTDA', 'Dispatched to destination airport'), ('AADA', 'Arrived at destination airport'), ('UIC', 'Undergoing import clearance'), ('PBPFD', 'Package being prepared for delivery'), ('DDE', 'Delivery details entered'), ('SPP', 'Shipping payment pending'), ('SPC', 'Shipping payment complete'), ('RFD', 'Ready for delivery'), ('OFD', 'Out for delivery'), ('D', 'Delivered'), ('RJ', 'Rejected')], max_length=6),
        ),
    ]
