# Generated by Django 3.2.5 on 2021-12-30 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_auto_20211210_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesapayment',
            name='amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
