# Generated by Django 3.2.5 on 2021-12-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_auto_20211231_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesapayment',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'Processing'), ('S', 'Successful'), ('F', 'Failed')], max_length=2, null=True),
        ),
    ]
