# Generated by Django 3.2.5 on 2022-02-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_alter_order_tracking_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.URLField(max_length=1000)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('identifier', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
