# Generated by Django 3.2.5 on 2022-03-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_auto_20220216_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='manager_user',
            field=models.BooleanField(default=False),
        ),
    ]
